### ISSUE TITLE
about dataset preprocessing

### ISSUE THREAD

**Issue by yyyloo** [divertingPan/STA-DRN#1]
Hello, could you please provide me with the code of dataset preprocessing? I would like to refer to it, because my programming ability is not very strong, and I will be very happy if I can get your help

**Comment by divertingPan** [comment]
[face_detect.py](https://github.com/divertingPan/utility_room/blob/master/face_detect.py): Crop faces from a series of video frame images. The images should be frames already exported from the video. To run the program directly, the path format for storing images should be `dataset_path/video_001/00001.jpg、dataset_path/video_001/00002.jpg`, and another model file [shape_predictor_68_face_landmarks.dat](https://github.com/divertingPan/utility_room/blob/master/shape_predictor_68_face_landmarks.dat) is also required.

**Comment by yyyloo** [comment]
前辈，谢谢你的开源代码。我已经复现出来



---Original---
From: "Diverting ***@***.***&gt;
Date: Sun, Mar 3, 2024 19:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [divertingPan/STA-DRN] about dataset preprocessing (Issue #1)




 
face_detect.py: Crop faces from a series of video frame images. The images should be frames already exported from the video. To run the program directly, the path format for storing images should be dataset_path/video_001/00001.jpg、dataset_path/video_001/00002.jpg, and another model file shape_predictor_68_face_landmarks.dat is also required.

**Comment by yyyloo** [comment]
Thank you very much!
