### ISSUE TITLE
Ask if you have the original AVEC2013 dataset

### ISSUE THREAD

**Issue by zyn00000** [divertingPan/STA-DRN#4]
Dear Diverting Pan:

I am very sorry to bother you here. Would I have the honor to ask you to take the time to read this e-mail?

I am a master's student in China. My research focuses on the intelligent detection of depression. I would like to ask if you have the original AVEC2013 dataset. I am in urgent need of this dataset to further my experiments.

If you have, shall you please share the raw video dataset with me? I assure you that the dataset will be used strictly for academic purposes, and your generous help will be acknowledged in our paper.

Thank you in advance for any help you can provide. I am looking forward to your early reply.

Best regards.

Sincerely,
zyn00000

**Comment by divertingPan** [comment]
Sorry, but we are not the original holders of this dataset, and we are not authorized to release it publicly on their behalf.
